# Generated by Django 5.2.11 on 2026-03-12 20:53

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetzwerkgeraetTyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('hat_funktion', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Netzwerkgerät-Typ',
                'verbose_name_plural': 'Netzwerkgerät-Typen',
                'ordering': ['kuerzel'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServerZweck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Server-Zweck',
                'verbose_name_plural': 'Server-Zwecke',
                'ordering': ['kuerzel'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_generator_standorte', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['kuerzel'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VmBereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'VM-Bereich',
                'verbose_name_plural': 'VM-Bereiche',
                'ordering': ['kuerzel'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VmFunktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'VM-Funktion',
                'verbose_name_plural': 'VM-Funktionen',
                'ordering': ['kuerzel'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NetzwerkgeraetFunktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('kuerzel', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Nur Großbuchstaben (A–Z) und Ziffern (0–9) erlaubt.')])),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funktionen', to='netbox_name_generator.netzwerkgeraettyp')),
            ],
            options={
                'verbose_name': 'Netzwerkgerät-Funktion',
                'verbose_name_plural': 'Netzwerkgerät-Funktionen',
                'ordering': ['typ__kuerzel', 'kuerzel'],
                'unique_together': {('typ', 'kuerzel')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
